# Single Neuron

In [1]:
# single neuron

weights = [0.04,0.023,0.015] # assuming 3 inputs are coming to the neuron
inputs  = [5,6,7] # these are the inputs to that neuron
bias = 2

output = sum([weights[i]*inputs[i] for i in range(len(weights))])+bias # this is the output from that neuron
print(output)

2.443


In [2]:
weights = [0.04,0.023,0.015] # assuming 3 inputs are coming to the neuron
inputs  = [5,6,7] # these are the inputs to that neuron
bias = 2

output = weights[0]*inputs[0]+weights[1]*inputs[1]+weights[2]*inputs[2]+bias # this is the output from that neuron
print(output)

2.443


# Multiple Neurons

In [3]:
# assuming 3 neurons in the layer we will get 3 outputs from that layer one from each layer

weights1 = [0.04,0.023,0.015] # assuming 3 inputs are coming to the neuron
weights2 = [0.024,0.05,0.02]
weights3 = [0.05,0.07,0.024]
inputs  = [5,6,7] # these are the inputs to that neuron
bias1 = 2
bias2 = 1
bias3 = 2


output1 = weights1[0]*inputs[0]+weights1[1]*inputs[1]+weights1[2]*inputs[2]+bias1 # this is the output from the neuron1
output2 = weights2[0]*inputs[0]+weights2[1]*inputs[1]+weights2[2]*inputs[2]+bias2 # output from neuron2
output3 = weights3[0]*inputs[0]+weights3[1]*inputs[1]+weights3[2]*inputs[2]+bias3 # output from neuron3

output = [weights1[0]*inputs[0]+weights1[1]*inputs[1]+weights1[2]*inputs[2]+bias1, weights2[0]*inputs[0]+weights2[1]*inputs[1]+weights2[2]*inputs[2]+bias2,
        weights3[0]*inputs[0]+weights3[1]*inputs[1]+weights3[2]*inputs[2]+bias3]
print(output1,output2,output3, output)

2.443 1.56 2.838 [2.443, 1.56, 2.838]


In [4]:

#method 2

weights = [weights1,weights2,weights3]
biases = [bias1,bias2,bias3]
inputs  = [1,2,3]

outputs = []
count = 0 
for wt,bias in zip(weights,biases):
    neuron_output = 0 
    for w,i in zip(wt,inputs):
        neuron_output+= w*i
        
    neuron_output+=bias
    count+=1
    outputs.append(neuron_output)
    
outputs

[2.1310000000000002, 1.184, 2.262]

#  With Numpy

In [5]:
import numpy as np

In [6]:
# Here y = WX+B acts similar to the linear equation. W varies slope varies, B varies interection on the axes varies which is similar to offset


In [7]:
outputs = np.dot(weights,inputs)+biases
outputs

array([2.131, 1.184, 2.262])

# Batch Processing

In [8]:
# Batch processing is used for faster learning of the model, generalizing the model
# Batch should be in a certain limit. If we take entire dataset a Batch it might lead to overfitting of the model

weights = [weights1,weights2,weights3]
biases = [bias1,bias2,bias3]

#lets take input in batches we have 3 batches of inputs

inputs = [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]

outputs = np.dot(inputs,weights)+biases

print(outputs)


[[2.238 1.333 2.127]
 [2.58  1.762 2.304]
 [2.922 2.191 2.481]
 [3.264 2.62  2.658]]


# Adding one more layer with 4 neurons

In [9]:
weights_2 = [[0.1,0.2,0.3],[-0.2,-0.1,0.5],[0.6,0.25,0.01],[0.2,0.5,0.7]]
biases_2 = [0.01,-0.05,0.04,-0.07]

# lets take input from previous layer as an input tho this layer
outputs = np.dot(outputs,np.array(weights_2).transpose())+biases_2
print(outputs)

[[1.1385  0.4326  1.73732 2.533  ]
 [1.3116  0.4098  2.05154 2.9398 ]
 [1.4847  0.387   2.36576 3.3466 ]
 [1.6578  0.3642  2.67998 3.7534 ]]


# Activation Function


Activation functions take the weighted sum of inputs and biases as an input and create an output

Why Activation functions are required ? To get the granular output. Easy to calculate the losses 

Before Activation functions there were threshold functions are step functions. These give the output 1 if x>0 else 0

There are no continuity at 0. When backpropagation introduced, with parital derivatives being used to calculate the loss, it will become tough to calculate the loss at 0

Also giving 1 or 0 as an output will be merely classification of two classes. 

So Activation functions are introduced inplace of threshold functions.


We have multiple activation functions

1. Sigmoid
2. ReLu
3. Tanh etc.

We will start with ReLU as it is easy to perform, fast and performs good

Relu : f(x) = x if x>0 else 0


In [3]:
# ReLU Activation function

# using list 


test_array = [-1,2,0.5,0.07,-0.35,-0.1,3]

for i,x in enumerate(test_array):
    if x<0:
        test_array[i] = 0 

print(test_array)
        
    
# using numpy
import numpy as np

test_array = [-1,2,0.5,0.07,-0.35,-0.1,3]
x = np.maximum(0,test_array)
print(x)

[0, 2, 0.5, 0.07, 0, 0, 3]
[0.   2.   0.5  0.07 0.   0.   3.  ]


In [25]:
# Softmax activation function  (e^xi/sum(e^xi))
"""
If we use the relu or anyother function the values can be random, will become tough to calculate losses

so exponential function is introduced which is softmax

it is defined by calculating exponent of the values and then divide each value by sum of all values

this is called normalization. It helps in calculating probabilities of various classes

So softmax is exponentition followed by normalization

"""

import math

test_array = [-1,2,0.5,0.07,-0.35,-0.1,3]
exponents = [math.e**x for x in test_array]
total = sum(exponents)
norms = [x/total for x in exponents]
print(norms)
print(sum(norms))



#using numpy
import numpy as np
test_array = [[-1,2,0.5],[0.07,-0.35,-0.1]] # two batches of inputs 
exponents_ = np.exp(test_array) 
print("exponents >> ",exponents_)
sums  = np.sum(np.exp(test_array),axis=1,keepdims=True) #axis 0: columns, axis 1: rows
print("sums>> ",sums)
norms = np.exp(test_array)/np.sum(np.exp(test_array),axis=1,keepdims=True)
print("norms >> ", norms)
total_probabilites = np.sum(norms,axis=1)
print("total_probabilities > ", total_probabilites)

[0.011434334402785674, 0.22966474583922664, 0.05124513151955508, 0.03333542411376307, 0.021902934401134184, 0.028123924471100584, 0.6242935052524349]
1.0
exponents >>  [[0.36787944 7.3890561  1.64872127]
 [1.07250818 0.70468809 0.90483742]]
sums>>  [[9.40565681]
 [2.68203369]]
norms >>  [[0.03911257 0.78559703 0.17529039]
 [0.39988617 0.26274394 0.33736989]]
total_probabilities >  [1. 1.]


2.718281828459045